/**
 * AIDirectedShort - Main Remotion composition for AI-directed viral shorts.
 * 
 * This composition combines:
 * - DynamicLayout for multi-speaker handling with smart crop
 * - AnimatedSubtitles for karaoke-style captions
 * - Jump-cut processing (via edit decision list)
 * - Platform-optimized output (TikTok, Reels, Shorts)
 * 
 * The composition receives all data from the backend via inputProps,
 * which is generated by the remotion_composer.py service.
 */

import React from 'react';
import {
  useCurrentFrame,
  useVideoConfig,
  Sequence,
  AbsoluteFill,
  Audio,
  interpolate,
  spring,
} from 'remotion';
import { SmartCrop, FaceCoordinate } from './SmartCrop';
import { AnimatedSubtitles, DiarizedWord, CaptionStyle, Platform } from './AnimatedSubtitles';
import { DynamicLayout, LayoutFrame, SpeakerSource } from './DynamicLayout';

// ============================================================================
// Type Definitions (matching backend models)
// ============================================================================

export interface KeepRange {
  start: number;
  end: number;
  clip_index?: number;
}

export interface EditDecisionList {
  job_id: string;
  clip_id?: string;
  original_duration: number;
  keep_ranges: KeepRange[];
  final_duration: number;
  time_saved: number;
}

export interface ViralClip {
  id: string;
  job_id: string;
  start_time: number;
  end_time: number;
  duration: number;
  virality_score: number;
  hook_type: string;
  hook_strength: number;
  suggested_titles: string[];
  emphasis_words: string[];
  summary: string;
  speakers: number[];
  transcript_text: string;
}

export interface AIDirectedShortProps {
  /** Job and clip identifiers */
  jobId: string;
  clipId: string;
  
  /** Video sources - can be single video or multiple speaker tracks */
  videoSources: string[];
  
  /** Viral clip metadata */
  viralClip?: ViralClip;
  
  /** Transcription with word timings */
  words: DiarizedWord[];
  
  /** Face tracking data per video source */
  faceTrackingData?: {
    [sourceIndex: number]: FaceCoordinate[];
  };
  
  /** Layout timeline for multi-speaker handling */
  layoutTimeline?: LayoutFrame[];
  
  /** Edit decision list for jump cuts */
  editDecisionList?: EditDecisionList;
  
  /** Source video dimensions (assumed same for all sources) */
  sourceWidth: number;
  sourceHeight: number;
  
  /** Caption styling */
  captionStyle?: CaptionStyle;
  
  /** Target platform */
  platform?: Platform;
  
  /** Whether to show captions */
  includeCaptions?: boolean;
  
  /** Background music URL */
  musicUrl?: string;
  
  /** Music volume (0-1) */
  musicVolume?: number;
  
  /** Main audio volume (0-1) */
  mainVolume?: number;
}

/**
 * Convert keep ranges to Remotion sequences
 * This handles jump-cut processing by only rendering the kept portions
 */
function useJumpCutSequences(
  editDecisionList: EditDecisionList | undefined,
  fps: number
): { ranges: KeepRange[]; totalFrames: number } {
  if (!editDecisionList || editDecisionList.keep_ranges.length === 0) {
    return { ranges: [], totalFrames: 0 };
  }
  
  const ranges = editDecisionList.keep_ranges;
  const totalFrames = Math.ceil(editDecisionList.final_duration * fps);
  
  return { ranges, totalFrames };
}

/**
 * Opening hook animation - attention-grabbing intro
 */
const HookAnimation: React.FC<{
  hookType: string;
  title?: string;
  duration: number;
}> = ({ hookType, title, duration }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  
  const progress = frame / (duration * fps);
  
  const scale = spring({
    frame,
    fps,
    from: 0.8,
    to: 1,
    config: { damping: 100 },
  });
  
  const opacity = interpolate(
    progress,
    [0, 0.2, 0.8, 1],
    [0, 1, 1, 0],
    { extrapolateRight: 'clamp' }
  );
  
  if (!title) return null;
  
  return (
    <AbsoluteFill
      style={{
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        opacity,
      }}
    >
      <div
        style={{
          transform: `scale(${scale})`,
          textAlign: 'center',
          padding: 40,
        }}
      >
        <span
          style={{
            fontSize: 24,
            color: '#FFD700',
            textTransform: 'uppercase',
            letterSpacing: 4,
            fontWeight: 600,
          }}
        >
          {hookType}
        </span>
        <h1
          style={{
            fontSize: 56,
            color: '#FFFFFF',
            fontWeight: 900,
            marginTop: 16,
            textShadow: '2px 2px 8px rgba(0, 0, 0, 0.8)',
          }}
        >
          {title}
        </h1>
      </div>
    </AbsoluteFill>
  );
};

/**
 * Call-to-action overlay at the end
 */
const CallToAction: React.FC<{
  platform: Platform;
}> = ({ platform }) => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();
  
  const slideUp = spring({
    frame,
    fps,
    from: 100,
    to: 0,
    config: { damping: 100 },
  });
  
  const platformCTA: Record<Platform, string> = {
    tiktok: 'Follow for more!',
    instagram: 'Double tap & follow!',
    youtube: 'Subscribe for more!',
  };
  
  return (
    <div
      style={{
        position: 'absolute',
        bottom: height * 0.25,
        left: 0,
        right: 0,
        display: 'flex',
        justifyContent: 'center',
        transform: `translateY(${slideUp}px)`,
      }}
    >
      <div
        style={{
          backgroundColor: '#FF0050',
          padding: '16px 32px',
          borderRadius: 40,
          boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
        }}
      >
        <span
          style={{
            color: '#FFFFFF',
            fontSize: 32,
            fontWeight: 800,
            textTransform: 'uppercase',
          }}
        >
          {platformCTA[platform]}
        </span>
      </div>
    </div>
  );
};

/**
 * Main AIDirectedShort composition
 */
export const AIDirectedShort: React.FC<AIDirectedShortProps> = ({
  jobId,
  clipId,
  videoSources,
  viralClip,
  words,
  faceTrackingData = {},
  layoutTimeline = [],
  editDecisionList,
  sourceWidth,
  sourceHeight,
  captionStyle = 'hormozi',
  platform = 'tiktok',
  includeCaptions = true,
  musicUrl,
  musicVolume = 0.1,
  mainVolume = 1,
}) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames, width, height } = useVideoConfig();
  
  // Calculate time adjustments for viral clip
  const clipStartTime = viralClip?.start_time || 0;
  const clipDuration = viralClip?.duration || durationInFrames / fps;
  
  // Build speaker sources for DynamicLayout
  const speakerSources: SpeakerSource[] = videoSources.map((src, index) => ({
    id: index,
    src,
    faceCoordinates: faceTrackingData[index] || [],
    sourceWidth,
    sourceHeight,
  }));
  
  // Filter words for this clip's time range
  const clipWords = words.filter(
    w => w.start >= clipStartTime && w.end <= clipStartTime + clipDuration
  ).map(w => ({
    ...w,
    start: w.start - clipStartTime,
    end: w.end - clipStartTime,
  }));
  
  // Emphasis words from viral clip selection
  const emphasisWords = viralClip?.emphasis_words || [];
  
  // Hook animation duration (first 1 second)
  const hookDurationFrames = Math.floor(fps * 1);
  
  // CTA duration (last 2 seconds)
  const ctaDurationFrames = Math.floor(fps * 2);
  const ctaStartFrame = durationInFrames - ctaDurationFrames;
  
  // Determine if we have multiple speakers
  const hasMultipleSpeakers = videoSources.length > 1 || layoutTimeline.length > 0;
  
  return (
    <AbsoluteFill style={{ backgroundColor: '#000000' }}>
      {/* Main video layer */}
      {hasMultipleSpeakers ? (
        <DynamicLayout
          speakers={speakerSources}
          layoutTimeline={layoutTimeline}
          defaultLayout="single_speaker"
          volume={mainVolume}
          startFrom={clipStartTime}
        />
      ) : (
        <SmartCrop
          src={videoSources[0]}
          faceCoordinates={faceTrackingData[0] || []}
          activeSpeaker={0}
          sourceWidth={sourceWidth}
          sourceHeight={sourceHeight}
          targetWidth={width}
          targetHeight={height}
          volume={mainVolume}
          startFrom={clipStartTime}
          endAt={clipStartTime + clipDuration}
        />
      )}
      
      {/* Animated subtitles */}
      {includeCaptions && clipWords.length > 0 && (
        <AnimatedSubtitles
          words={clipWords}
          emphasisWords={emphasisWords}
          style={captionStyle}
          platform={platform}
          maxWordsPerLine={4}
          verticalPosition={0.78}
        />
      )}
      
      {/* Opening hook animation */}
      {viralClip && frame < hookDurationFrames && (
        <Sequence from={0} durationInFrames={hookDurationFrames}>
          <HookAnimation
            hookType={viralClip.hook_type}
            title={viralClip.suggested_titles[0]}
            duration={1}
          />
        </Sequence>
      )}
      
      {/* End CTA */}
      {frame >= ctaStartFrame && (
        <Sequence from={ctaStartFrame} durationInFrames={ctaDurationFrames}>
          <CallToAction platform={platform} />
        </Sequence>
      )}
      
      {/* Background music */}
      {musicUrl && (
        <Audio
          src={musicUrl}
          volume={musicVolume}
          startFrom={0}
        />
      )}
    </AbsoluteFill>
  );
};

export default AIDirectedShort;
